[reports]
ignore = [ "C-G8"]
severity_levels = true
merge = "multiline" # multiline, multiplier

[reports.text]
# [level][code][description]
# eg: MINOR: C-L4: misplaced curly bracket
code = true
description = true
level = false
