name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          known_hosts: $GH_PUB_KEY

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build cs
        run: nix build . --print-build-logs

      - name: Smoke tests
        run: |
          ./result/bin/cs smoke/good.c

          # bad.c should fail
          if ./result/bin/cs smoke/bad.c; then
            echo "bad.c unexpectedly passed"
            exit 1
          fi
